#27: WebAPI (command-endpoints)
Mishanull/AquatimeCupSystem pull request #32
Opened 2024-05-01 13:29 UTC by banny99

2024-05-01 17:21 UTC, Mishanull requested changes
There are a bunch of minor comments, like removing commented out stuff, but also a bunch of questions and stuff that needs a tad bit of refactoring. So I'll only approve this after the comments have been resolved one way or another.

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Presentation.WebAPI/Endpoints/CreateUser.cs
> +        // return Ok()
can you remove commented out stuff?

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Presentation.WebAPI/Endpoints/AddCup.cs
> +        // return Ok(((Result<CupAgg>)responseResult).Value!.Id.Value); //-if retrieving the whole CupAgg object on creation
remove line 32-34

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Presentation.WebAPI/Common/QueryEndpoint.cs
why is this entire class commented out? Don't we need it?

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Presentation.WebAPI/Server.Presentation.WebAPI.csproj
> +        <Nullable>enable</Nullable>
Maybe this project should be Infrastructure.WebAPI? We do not consider the api to be a presentation layer and we do not mention a presentation layer anywhere, I was thinking maybe we could do this. Also remove the RootNamespace after renaming

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Presentation.WebAPI/Server.WebApplication.http
> +GET {{Server.WebApplication_HostAddress}}/weatherforecast/
remove this file

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Tools.Server.ObjectMapper/IMappingConfig.cs
> +
maybe it's a bit overkill to have a mapper, but we can use it

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Core.Application/AppEntry/UowSaveDispatcher.cs
> +        return dispatchResult;
why are we returning the dispatchResult? The return type is Result, so we do not store any value. If the dispatchResult contains errors, it will be handled in the if statement. This doesn't change anything really.

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Core.Application/Handlers/AddCupActionWithMeasurementsToCupCommandHandler.cs
> +        //return CupActionId as string
remove

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Core.Application/Handlers/RemoveCupCommandHandler.cs
> +        // var userRemovesCupService = new UserRemovesCup(cupRepository);
remove commented out code

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Infrastructure.DomainModelPersistence/Common/RepositoryEfcBase.cs
> +        // TAgg? root = await context.Set<TAgg>().FirstOrDefaultAsync(x => x.Id == id);
remove

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Infrastructure.DomainModelPersistence/Common/RepositoryEfcBase.cs
> +            // var addedEntityId = entityEntry.Entity.Id; // Id as TId
remove

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Infrastructure.DomainModelPersistence/Services/EmailCheck.cs
> +            throw new ArgumentException(emailResult.Errors.ToString());
what's going on here? Why is it a bool and not a Result<bool>? We should not do exceptions here. And this method's single responsibility should be just to verify the existence of the email imo, not to verify its validity. That is done by the creation of the command. Use the result pattern instead of exceptions, i.e lines from 19-28 should be kept.

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.IntegrationTests/Utils/ServerErrorMapper.cs
> +        // var errorType = Enumeration.FromValue<ErrorType>(errorResponse.Type.Value);
remove

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.IntegrationTests/WebApiTests/PredictCupActionTests.cs
> +public class PredictCupActionTests
I think this can be renamed to PredictCupActionEndpointTests

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.IntegrationTests/WebApiTests/SetLiquidTypeTests.cs
> +        // Assert.Equal(newLiquidType.Value, cupResult.Value!.LiquidType.Value); //this does not work?
remove

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.IntegrationTests/WebApiTests/WebAppFactory.cs
> +            // services.RemoveAll(typeof(DbContextOptions<ReadDbContext>));
remove

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Presentation.WebAPI/Endpoints/PredictCupAction.cs
> +        // var commandResult = PredictActionCommand.Create(request.CupActionId, predictionService);
remove

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Presentation.WebAPI/Endpoints/RemoveLiquidIntakeGoal.cs
> +    //ToDo: does not fail but does not remove the goal either!?
this was fixed right? if so, remove the todo

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Infrastructure.DomainModelPersistence/Services/PredictionService.cs
> +    private readonly HttpClient _httpClient = new();
this is not correctly placed. It does not have anything at all to do with DomainModelPersistence. It should be either in a project of its own, or in the web api project.

2024-05-01 17:21 UTC, Mishanull commented on DashboardServer/Server.Infrastructure.DomainModelPersistence/Services/PredictionService.cs
> +            var response = await _httpClient.PostAsJsonAsync("http://localhost:5000/predict", cupAction);
otherwise this is nice, maybe we didn't need it right now but it's good to have, just move it somewhere where it makes sense.

2024-05-02 16:26 UTC, banny99 commented on DashboardServer/Server.Presentation.WebAPI/Common/QueryEndpoint.cs
we do. it is because i need the IQueryDispatcher there which is done in your branch. i could cherry-pick it I know, but I didn't need it for now so I just left it commented out.

2024-05-02 16:30 UTC, banny99 commented on DashboardServer/Server.IntegrationTests/WebApiTests/WebAppFactory.cs
> +            // services.RemoveAll(typeof(DbContextOptions<ReadDbContext>));
but these will be there.. they are not again just because I do not have those.

2024-05-02 16:32 UTC, banny99 commented on DashboardServer/Server.Presentation.WebAPI/Endpoints/PredictCupAction.cs
> +        // var commandResult = PredictActionCommand.Create(request.CupActionId, predictionService);
the commented one is the correct one, it is just not used now because we do not have the Prediction service yet.

2024-05-02 16:36 UTC, banny99 commented on DashboardServer/Server.Infrastructure.DomainModelPersistence/Services/PredictionService.cs
> +    private readonly HttpClient _httpClient = new();
it does,, it is updating the CupAction in the DB, which is its main job actually. to take stuff from the DB (the cup action and its measurements, do the prediction and then update the DB accordingly). But yeah you are right, should probably be separate. maybe Server.Infrastructure.PredictionService ?

2024-05-02 16:40 UTC, Mishanull commented on DashboardServer/Server.IntegrationTests/WebApiTests/WebAppFactory.cs
> +            // services.RemoveAll(typeof(DbContextOptions<ReadDbContext>));
yeah sorry I did it out of force of habit :)))

2024-05-02 16:41 UTC, Mishanull commented on DashboardServer/Server.Infrastructure.DomainModelPersistence/Services/PredictionService.cs
> +    private readonly HttpClient _httpClient = new();
yeah perhaps, could be called PredictionClient. since that is what we are reffering to in the docs

2024-05-02 16:41 UTC, Mishanull commented on DashboardServer/Server.Infrastructure.DomainModelPersistence/Services/PredictionService.cs
> +    private readonly HttpClient _httpClient = new();
yeah, but the update the db part should be in the handler, the service should just get the result and that's it's only responsibility

2024-05-02 16:55 UTC, banny99 commented on DashboardServer/Server.Infrastructure.DomainModelPersistence/Services/EmailCheck.cs
> +            throw new ArgumentException(emailResult.Errors.ToString());
i think thats how was the interface defined. but you are right. 
Also checking if it is valid email does not belong here, but the FindByEmail requires the email as the Email-value object, so I need to create it which does the validation also.
And should it be async?

2024-05-02 17:18 UTC, Mishanull commented on DashboardServer/Server.Infrastructure.DomainModelPersistence/Services/EmailCheck.cs
> +            throw new ArgumentException(emailResult.Errors.ToString());
yeah the interface was defined that way, it should be changed as well. And yeah it should also be async since the findByEmail method is async as well on the repo.

2024-05-02 17:21 UTC, banny99 commented on DashboardServer/Server.IntegrationTests/WebApiTests/PredictCupActionTests.cs
> +public class PredictCupActionTests
why? none of the endpoint/controller classes nor other endpoint-tests are called in that way

2024-05-02 17:25 UTC, banny99 commented on DashboardServer/Server.IntegrationTests/WebApiTests/SetLiquidTypeTests.cs
> +        // Assert.Equal(newLiquidType.Value, cupResult.Value!.LiquidType.Value); //this does not work?
but that is sth that needs to be there but does not work at the moment. it is that Liquid-type issue I told you about, that the display value is correct but the value is not, therefore the Equals returns true even though it is the same type.

2024-05-02 17:28 UTC, Mishanull commented on DashboardServer/Server.IntegrationTests/WebApiTests/PredictCupActionTests.cs
> +public class PredictCupActionTests
oh ok, I thought we were going to name them that way, sorry, like to not be confused with other stuff, but it's fine. I can do that renaming when I make the query endpoints.

2024-05-02 18:07 UTC, banny99 commented on DashboardServer/Server.Core.Application/AppEntry/UowSaveDispatcher.cs
> +        return dispatchResult;
i do store a value. I am returning an Id-string if it the command was creation of an entity

2024-05-02 18:22 UTC, Mishanull submitted a review, later dismissed

2024-05-02 18:22 UTC, Mishanull commented on DashboardServer/Server.Infrastructure.DomainModelPersistence/Services/EmailCheck.cs
> +        }
this still is not necessary, but  I can remove it myself

2024-05-02 18:24 UTC, banny99 commented on DashboardServer/Server.Infrastructure.DomainModelPersistence/Services/EmailCheck.cs
> +        }
so should i just create it without checking?

2024-05-02 18:52 UTC, Mishanull commented on DashboardServer/Server.Infrastructure.DomainModelPersistence/Services/EmailCheck.cs
> +        }
yeah, cause the validity of the email is already checked when creating the command, so it is not necessary to do it here. But only if you want to, otherwise I can modify it.

2024-05-04 20:23 UTC, Mishanull approved these changes

2024-05-04 20:23 UTC, merged